### ISSUE TITLE
版本升级报空问题

### ISSUE THREAD

**Issue by meixinqing** [zs9024/quick_uicode#2]
升级成unity2018.2.0版本报空是为啥？（2018.1.8版本可以用）
_visibleRect = GUIHelper.VisibleRect();（报空语句）

NullReferenceException: Object reference not set to an instance of an object
Rotorz.ReorderableList.ReorderableListControl.PrepareState (Int32 controlID, IReorderableListAdaptor adaptor) (at Assets/QuickCode/Rotorz/ReorderableListControl.cs:586)
希望大神指导一下

**Comment by zs9024** [comment]
ReorderableList是第三方的序列化list的工具，应该是unity版本太高了还没支持
